name: 'Build Image'

on:
  push:

  release:
    types:
      - published

  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

jobs:
  build:
    uses: SlashNephy/.github/.github/workflows/docker-build.yml@master
    with:
      image-name: ghcr.io/slashnephy/dump-ch2
      image-platforms: linux/amd64,linux/arm64
